version : '3'
services:
  mio-app:
    image: smukk9/app-msandeep.io:2.0
    expose:
      - 80
    environment:
      VIRTUAL_HOST: msandeep.io
      LETSENCRYPT_HOST: msandeep.io
      LETSENCRYPT_EMAIL: smukk9@gmail.com
    container_name: mio-app

networks:
      default:
        external:
            name: nginx-proxy
