version : '2'
services:
  mysqldbserver:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: demo
      MYSQL_PASSWORD: dbp4ss
      MYSQL_USER: dbuser
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: p4SSW0rd

      DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
    container_name: mio-mysql
    volumes:
      - mio-mysqlvolume:/var/lib/mysql

  springappserver:
    image: smukk9/msandeep-io:1.0
    ports:
      - "8080:8080"
    links:
      - mysqldbserver
    depends_on:
      - mysqldbserver
    container_name: mio-app
volumes:
    mio-mysqlvolume:
      external: true