CREATE TABLE "USER" (
  USER_ID  SERIAL PRIMARY KEY NOT NULL,
  ACTIVE VARCHAR(255) NOT NULL,
  CREATE_DATE VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  MODIFY_DATE VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  USERNAME VARCHAR(255) NOT NULL
);

CREATE TABLE "TAG" (
  TAG_ID  SERIAL PRIMARY KEY NOT NULL,
  CREATE_DATE VARCHAR(255) NOT NULL,
  MODIFY_DATE VARCHAR(255) NOT NULL,
  TAGNAME VARCHAR(255) NOT NULL


);

CREATE TABLE "ARTICLE" (
  ARTICLE_ID  SERIAL  PRIMARY KEY NOT NULL,
  CREATE_DATE VARCHAR(255) NOT NULL,
  MODIFY_DATE VARCHAR(255) NOT NULL,
  TITLE VARCHAR(255) NOT NULL,              
  USER_ID VARCHAR(255) NOT NULL REFERENCES USER (USER_ID),
  CONTENT TEXT NOT NULL


);

CREATE TABLE "ARTICLE_TAG" (
  ARTICLE_ID VARCHAR(255) NOT NULL  references ARTICLE (ARTICLE_ID),
  TAG_ID VARCHAR(255) NOT NULL  references TAG (TAG_ID)

);

CREATE TABLE "ROLE" (
  ROLE_ID  SERIAL PRIMARY KEY NOT NULL,
  CREATE_DATE VARCHAR(255) NOT NULL,
  MODIFY_DATE VARCHAR(255) NOT NULL,
  ROLE VARCHAR(255) NOT NULL,
  PRIMARY KEY (ROLE_ID)

);

CREATE TABLE "USER_ROLE" (
  USER_ID VARCHAR(255) NOT NULL  references USER (USER_ID),
  ROLE_ID VARCHAR(255) NOT NULL  references ROLE (ROLE_ID)

);
